apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        log
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4
        cache 30
        loop
        reload
        loadbalance
        file /etc/coredns/zones/db.dev.example.io dev.example.io {
          upstream
        }
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
